### ISSUE TITLE
No longer able to build site

### ISSUE THREAD

**Issue by Gerrit0** [dsherret/ts-ast-viewer#153]
I had ideas I wanted to play with based off this viewer, but it looks like *something* doesn't work quite right anymore, this is with a fresh install, I gave Node 22 a try too, with the same issue

```console
main ~/Desktop/ts-ast-viewer> node --version
v20.10.0
main ~/Desktop/ts-ast-viewer> deno --version
deno 1.44.1+3765e6b (canary, x86_64-unknown-linux-gnu)
v8 12.6.228.9
typescript 5.4.5
main ~/Desktop/ts-ast-viewer> deno task build
Task build DENO_V8_FLAGS=--max_old_space_size=10240 vite build && cp CNAME .nojekyll dist/
Warning Sloppy imports are not recommended and have a negative impact on performance.
vite v5.2.9 building for production...
✓ 72 modules transformed.
x Build failed in 441ms
error during build:
RollupError: Expected '}', got '<eof>'
    at getRollupError (file:///home/gerrit/Desktop/ts-ast-viewer/node_modules/rollup/dist/es/shared/parseAst.js:392:41)
    at ParseError.initialise (file:///home/gerrit/Desktop/ts-ast-viewer/node_modules/rollup/dist/es/shared/node-entry.js:11170:28)
    at convertNode (file:///home/gerrit/Desktop/ts-ast-viewer/node_modules/rollup/dist/es/shared/node-entry.js:12915:10)
    at convertProgram (file:///home/gerrit/Desktop/ts-ast-viewer/node_modules/rollup/dist/es/shared/node-entry.js:12232:12)
    at Module.setSource (file:///home/gerrit/Desktop/ts-ast-viewer/node_modules/rollup/dist/es/shared/node-entry.js:14076:24)
    at async ModuleLoader.addModuleSource (file:///home/gerrit/Desktop/ts-ast-viewer/node_modules/rollup/dist/es/shared/node-entry.js:18729:13)
exit 1
main ~/Desktop/ts-ast-viewer> 
```

`deno task test` does run successfully (with lots of noise about "sloppy imports"), which implies I didn't set up deno incorrectly somehow...

I also tried following the steps laid out in ci.yml, with similar problems.... not really sure where to go from here. I miss the simple `npm install && npm run build` I used to be able to do.

**Comment by dsherret** [comment]
Use `deno upgrade --version 1.44.1`. It seems like a recent bug in deno canary.

> I miss the simple npm install && npm run build I used to be able to do.

Sorry, I'm using this repo to find and fix bugs in Deno's upcoming 2.0 version.

**Comment by dsherret** [comment]
Seems to break on https://github.com/denoland/deno/commit/e3b2ee183bc7497ec0432bc764678f5eda6495a7

**Comment by dsherret** [comment]
Fix at https://github.com/denoland/deno/pull/24193

Will be able to close this with the Deno release tonight.

**Comment by dsherret** [comment]
This is passing again now: https://github.com/dsherret/ts-ast-viewer/actions/runs/9495212391
